version: '3.3'
services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    build: .
    ports:
      - "8080:8080"
    environment:
      - KC_HOSTNAME=localhost
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    command:
      - start-dev
    volumes:
      - ./build/libs:/opt/keycloak/providers
      - ./themes/test:/opt/keycloak/themes/test