<project 
    xmlns="http://maven.apache.org/POM/4.0.0" 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>io.github.slemke</groupId>
    <artifactId>keycloak-backup-email</artifactId>
    <version>0.0.1</version>
    <name>keycloak-backup-email</name>
    <description>A Keycloak Required Action to force a user to provide an email before completing the auth process.</description>
    <url>https://github.com/slemke/keycloak-backup-email</url>
    <inceptionYear>2024</inceptionYear>
    <licenses>
        <license>
            <name>Apache License, Version 2.0</name>
            <url>https://www.apache.org/licenses/LICENSE-2.0.txt</url>
            <distribution>repo</distribution>
        </license>
    </licenses>
    <developers>
        <developer>
            <id>slemke</id>
            <name>Sascha Lemke</name>
        </developer>
    </developers>
    <scm>
        <connection>scm:git:https://github.com/slemke/keycloak-backup-email.git</connection>
        <developerConnection>scm:git:https://github.com/slemke/keycloak-backup-email.git</developerConnection>
        <url>https://github.com/slemke/keycloak-backup-email.git</url>
        <tag>HEAD</tag>
    </scm>
    <properties>
        <maven.compiler.source>25</maven.compiler.source>
        <maven.compiler.target>25</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>
    <dependencies>
        <dependency>
            <groupId>org.keycloak</groupId>
            <artifactId>keycloak-server-spi-private</artifactId>
            <version>26.7.2</version>
        </dependency>

        <dependency>
            <groupId>org.keycloak</groupId>
            <artifactId>keycloak-server-spi</artifactId>
            <version>26.7.2</version>
        </dependency>

        <dependency>
            <groupId>org.keycloak</groupId>
            <artifactId>keycloak-model-jpa</artifactId>
            <version>26.7.2</version>
        </dependency>

        <dependency>
            <groupId>org.keycloak</groupId>
            <artifactId>keycloak-services</artifactId>
            <version>26.7.2</version>
        </dependency>
    </dependencies>
</project>